---
resources:
- name: concourse-examples
  type: git
  icon: github
  check_every: 30m
  source:
    uri: https://github.com/BerGod/examples

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  build_log_retention:
    builds: 50
  plan:
  - get: concourse-examples
    trigger: true
  - set_pipeline: self
    file: concourse-examples/pipelines/set-pipelines-test-vars.yml

- name: set-example-pipelines
  public: true
  build_log_retention:
    builds: 50
  plan:
  - get: concourse-examples
    trigger: true
    passed: [set-self]
  - set_pipeline: pipeline-vars-with-varsFilesBefore
    file: concourse-examples/pipelines/pipeline-vars.yml
    var_files:
      - concourse-examples/pipelines/vars-file.yml
    vars:
      first: second
      number: "9001"
      hello: OVVERIDED
  - set_pipeline: pipeline-vars-with-varsAfter
    file: concourse-examples/pipelines/pipeline-vars.yml
    var_files:
      - concourse-examples/pipelines/vars-file.yml
    vars:
      first: second
      number: "9001"
      hello: OVVERIDED
  - set_pipeline: pipeline-with2varsFile
    file: concourse-examples/pipelines/pipeline-vars.yml
    var_files:
      - concourse-examples/pipelines/vars-file.yml
      - concourse-examples/pipelines/second-vars-file.yml
    